### ISSUE TITLE
Error reported during caffe compilation

### ISSUE THREAD

**Issue by ADstudyer** [yjxiong/caffe#220]
Hello author！I'm sorry to disturb you. I can't install caffe's dependencies according to the sudo instructions you gave, so I installed it manually. The following problems occurred in compiling caffe:

[ 83%] Linking CXX executable extract_features
/usr/bin/ld: CMakeFiles/extract_features.dir/extract_features.cpp.o: undefined reference to symbol '_ZN6google8protobuf8internal12kEmptyStringB5cxx11E'
/home/developers/xianyun/app/local/lib/libprotobuf.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
tools/CMakeFiles/extract_features.dir/build.make:143: recipe for target 'tools/extract_features' failed
make[2]: *** [tools/extract_features] Error 1
CMakeFiles/Makefile2:438: recipe for target 'tools/CMakeFiles/extract_features.dir/all' failed
make[1]: *** [tools/CMakeFiles/extract_features.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

I checked quite a lot of information, and reinstalled my protobuf 2.5.0, 2.6.1, including the latest 3.6.1, but they all reported the same error. May I ask the author what version of your protobuf is? Or can you indicate what caused this problem? Thank you for your help!

**Comment by yjxiong** [comment]
This code should compile with protobuf 2.6.1. I haven't seen this error before. Google suggests that this may be helpful:

https://github.com/grpc/grpc/issues/9549
